### ISSUE TITLE
Rye shims not added to one's path

### ISSUE THREAD

**Issue by doolio** [Azuki-bar/asdf-rye#5]
**Describe the bug**

Rye by default creates its own shims `python` and `python3` in`~/.rye/shims`. However, these are **not** added to one's path by default.

**Steps to reproduce**

````shell
$ python --version  # check system python version
$ asdf install rye latest  # install latest version of rye with asdf
$ asdf global rye <version>  # set the global version of rye to be the version installed
$ rye new rye-demo  # create a rye managed python project; this installs the latest python version and pins the project to it
$ cd rye-demo
$ rye sync # creates the virtual environment at `./.venv` with the rye installed python version
$ rye shell # spawns a subshell with the virtualenv activated
$ python --version  # matches system version rather than that installed by rye
````

**Expected behavior**

Rye's shims are added to one's path so that `python` or `python3` in the virtualenv point to the expected python version.

**Comment by Azuki-bar** [comment]
Sorry, In my environment, `$ python --version  # matches system version rather than that installed by rye` is not reproduced.
the `$PATH`value in venv shell includes `./.venv/bin`.
and at `.venv/bin`, this directory includes python interpreter with specified by rye.

```shell

(venv) $ which python
/home/azukibar/rye-demo/.venv/bin/python
(venv) $ readlink .venv/bin/python
/home/azukibar/.rye/py/cpython@3.11.5/install/bin/python3
```

I think that expected behavior implementation is not needed now.

please pass more information. Please be careful not to post sensitive information.
- OS
- shell
- local python version
- `which python` executed result in local and venv shell.
- `$PATH`

If you can provide more information, I may be able to investigate the cause.

**Comment by doolio** [comment]
Thanks. It seems `rye shell` does not in fact activate the virtual environment despite its description stating it does. It does though set `VIRTUAL_ENV`. I will raise this with the `rye` project.

![image](https://github.com/Azuki-bar/asdf-rye/assets/13859009/4c6b67c6-606b-4112-8e88-fc18884badd6)

![image](https://github.com/Azuki-bar/asdf-rye/assets/13859009/b751b7b2-ef8a-40ee-af4d-8b96f914c289)
